package org.rdkit.knime.nodes.moleculecatalogfilter;

import java.util.Arrays;

import org.knime.core.node.InvalidSettingsException;
import org.knime.core.node.NodeSettingsRO;
import org.knime.core.node.NodeSettingsWO;
import org.knime.core.webui.node.dialog.defaultdialog.DefaultNodeSettings;
import org.knime.core.webui.node.dialog.defaultdialog.DefaultNodeSettings.DefaultNodeSettingsContext;
import org.knime.core.webui.node.dialog.defaultdialog.layout.After;
import org.knime.core.webui.node.dialog.defaultdialog.layout.Layout;
import org.knime.core.webui.node.dialog.defaultdialog.layout.Section;
import org.knime.core.webui.node.dialog.defaultdialog.persistence.field.FieldNodeSettingsPersistor;
import org.knime.core.webui.node.dialog.defaultdialog.persistence.field.Persist;
import org.knime.core.webui.node.dialog.defaultdialog.widget.ChoicesProvider;
import org.knime.core.webui.node.dialog.defaultdialog.widget.ChoicesWidget;
import org.knime.core.webui.node.dialog.defaultdialog.widget.TextInputWidget;
import org.knime.core.webui.node.dialog.defaultdialog.widget.ValueSwitchWidget;
import org.knime.core.webui.node.dialog.defaultdialog.widget.Widget;
import org.knime.core.webui.node.dialog.defaultdialog.widget.choices.IdAndText;
import org.knime.core.webui.node.dialog.defaultdialog.widget.choices.ColumnChoicesProviderUtil.AllColumnChoicesProvider;
import org.rdkit.knime.util.RDKitMoleculeColumnChoicesProvider;

/**
 * Settings for the RDKit Molecule Catalog Filter node using the webui
 * framework.
 * 
 * @author Marc Lehner
 */
public final class RDKitMoleculeCatalogFilterNodeSettings implements DefaultNodeSettings {
	
	static final class FilterCatalogChoices implements ChoicesProvider {
		@Override
		public String[] choices(final DefaultNodeSettingsContext context) {
			return Arrays.stream(FilterCatalogEnum.values()).map(Enum::name).toArray(String[]::new);
		}
	}

	
	public enum FilterCatalogEnum{
		PAINS_A,
		PAINS_B,
		PAINS_C,
		PAINS,
		BRENK,
		NIH,
		ZINC,
		CHEMBL_Glaxo, 
		CHEMBL_Dundee,
		CHEMBL_BMS,
		CHEMBL_SureChEMBL,
		CHEMBL_MLSMR,
		CHEMBL_Inpharmatica,
		CHEMBL_LINT,
		CHEMBL,
		ALL,
	}
	
	static final class FilterCatalogArrayPersistor implements FieldNodeSettingsPersistor<String[]> {
        private static final String KEY = "catalogs";

        @Override
        public String[] load(final NodeSettingsRO settings) throws InvalidSettingsException {
            return settings.getStringArray(KEY);
        }

        @Override
        public void save(final String[] obj, final NodeSettingsWO settings) {
            settings.addStringArray(KEY, obj);
        }

        @Override
        public String[] getConfigKeys() {
            return new String[]{KEY};
        }
    }
	
	
	
	static final class AtomListHandlingChoices implements ChoicesProvider {		
		@Override
		public IdAndText[] choicesWithIdAndText(final DefaultNodeSettingsContext context) {
			return Arrays.stream(AtomListHandling.values()).map(AtomListHandling::toIdAndText).toArray(IdAndText[]::new);
		}
	}
	
	
    @Section(title = "Input Configuration")
    interface InputSection {}

    @Section(title = "Filter Catalogs")
    @After(InputSection.class)
    interface FilterCatalogSection {}

    @Section(title = "Output Configuration")
    @After(FilterCatalogSection.class)
    interface OutputSection {}

    @Persist(configKey = "input_column")
    @Widget(title = "Input Molecule Column",
            description = "Select the input column that contains the RDKit Molecule.")
    @ChoicesWidget(choices = RDKitMoleculeColumnChoicesProvider.class)
    @Layout(InputSection.class)
    String m_inputColumn;

    @Persist(configKey = "catalogs", customPersistor = FilterCatalogArrayPersistor.class)
    @Widget(
        title = "Filter Catalogs",
        description = "Select the filter catalogs to apply. Multiple catalogs can be selected."
    )
    @ChoicesWidget(choices = FilterCatalogChoices.class)
    @Layout(FilterCatalogSection.class)
    String[] m_catalogs;

    @Persist(configKey = "output_column_prefix")
    @Widget(
        title = "Output Column Prefix",
        description = "Specify a prefix for the result columns generated by the node."
    )
    @TextInputWidget
    @Layout(OutputSection.class)
    String m_outputColumnPrefix = "";

    @Persist(configKey = "generate_atom_list")
    @Widget(
        title = "Atom List Handling",
        description = "Specify how atom lists should be generated for matching filters."
    )
    @ChoicesWidget(choices = AtomListHandlingChoices.class)
    @Layout(OutputSection.class)
    AtomListHandling m_generateAtomList = AtomListHandling.None;
}